export const RECEIVE_INSTITUTIONS = 'RECEIVE_INSTITUTIONS';
export const REJECT_INSTITUTIONS = 'REJECT_INSTITUTIONS';

export const RECEIVE_GROUPS = 'RECEIVE_GROUPS';
export const REJECT_GROUPS = 'REJECT_GROUPS';

export const RECEIVE_EVENTS = 'RECEIVE_EVENTS';
export const REJECT_EVENTS = 'REJECT_EVENTS';

