export const INSTITUTIONS = {
    RECEIVE: 'RECEIVE_INSTITUTIONS',
    REJECT: 'REJECT_INSTITUTIONS',
};

export const GROUPS = {
    RECEIVE: 'RECEIVE_GROUPS',
    REJECT: 'REJECT_GROUPS',
};

export const TEACHERS = {
    RECEIVE: 'RECEIVE_TEACHERS',
    REJECT: 'REJECT_TEACHERS',
};
