export const REGISTRATION_SUBMIT = 'REGISTRATION_SUBMIT';
export const REGISTRATION_GET_LOCATIONS = 'REGISTRATION_GET_LOCATIONS';
export const REGISTRATION_LOCATIONS_REQUEST ='REGISTRATION_LOCATIONS_REQUEST';
export const REGISTRATION_SUBMIT_REQUEST = 'REGISTRATION_SUBMIT_REQUEST';