export const REGISTRATION_LOCATIONS_REQUEST = 'REGISTRATION_LOCATIONS_REQUEST';
export const REGISTRATION_LOCATIONS_RESPONSE = 'REGISTRATION_LOCATIONS_RESPONSE';
export const REGISTRATION_SUBMIT_RESPONSE = 'REGISTRATION_SUBMIT_RESPONSE';
export const REGISTRATION_SUBMIT_REQUEST = 'REGISTRATION_SUBMIT_REQUEST';
